"use client";

import { useEffect, useMemo, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { appMessage } from "@/lib/message";
import { Button } from "@/components/ui/button";
import { Combobox, type ComboboxOption } from "@/components/ui/combobox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";
import type { DimensionPackOption, ReviewDimensionItem } from "@/features/template-designer/types/review-dimension";
import {
  createEmptyReviewDimension,
  sumReviewDimensionWeights,
  toReviewDimensionPayload,
  validateReviewDimensions,
} from "@/features/template-designer/utils/review-dimension-utils";
import {
  buildReviewPromptFromDimensions,
  isAutoGeneratedReviewPrompt,
} from "../utils/review-prompt-builder";
import { useDesignerReviewConfigStore } from "@/features/template-designer/stores/designer-review-config-store";
import {
  applyDimensionPack,
  fetchLlmCatalog,
  fetchReviewConfig,
  generateReviewPromptAssist,
  listDimensionPackOptions,
  saveReviewConfig,
  type LlmCatalogProviderOption,
  type ReviewPromptAssistMode,
  type ReviewPromptAssistResult,
} from "../review-config-api";
import { ReviewPromptProEditor } from "./ReviewPromptProEditor";
import { ReviewWorkflowEditor } from "./ReviewWorkflowEditor";
import { DEFAULT_REVIEW_WORKFLOW_LEVELS, type ReviewWorkflowLevelItem } from "../review-workflow-types";
import { validateReviewWorkflowLevels } from "../review-workflow-utils";

type ReviewConfigMode = "standard" | "pro";

interface TemplateReviewConfigPanelProps {
  versionId: string;
  editable: boolean;
  onSaved?: () => void;
  onCancel?: () => void;
}

function patchDimension(
  items: ReviewDimensionItem[],
  index: number,
  patch: Partial<ReviewDimensionItem>,
): ReviewDimensionItem[] {
  return items.map((item, itemIndex) => (itemIndex === index ? { ...item, ...patch } : item));
}

function dimensionCardTitle(item: ReviewDimensionItem, index: number): string {
  const name = item.dimensionName.trim();
  if (name) return name;
  const code = item.dimensionKey.trim();
  if (code) return code;
  return `维度 ${index + 1}`;
}

function ReviewDimensionEditorPanel({
  item,
  index,
  editable,
  proMode,
  onChange,
  onRemove,
}: {
  item: ReviewDimensionItem;
  index: number;
  editable: boolean;
  proMode: boolean;
  onChange: (patch: Partial<ReviewDimensionItem>) => void;
  onRemove: () => void;
}) {
  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="flex items-start justify-between gap-3 border-b border-border px-5 py-4">
        <div>
          <h3 className="text-sm font-semibold text-foreground">
            {dimensionCardTitle(item, index)}
          </h3>
          <p className="mt-1 text-xs text-muted-foreground">编辑该维度的权重、阈值与专项提示词</p>
        </div>
        <Button type="button" variant="ghost" size="sm" disabled={!editable} onClick={onRemove}>
          <Trash2 className="mr-1 h-4 w-4" />
          删除
        </Button>
      </div>
      <div className="min-h-0 flex-1 overflow-auto px-5 py-4">
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">维度编码</label>
            <Input
              value={item.dimensionKey}
              disabled={!editable}
              placeholder="QUALITY_SCORE"
              onChange={(event) => onChange({ dimensionKey: event.target.value })}
            />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">维度名称</label>
            <Input
              value={item.dimensionName}
              disabled={!editable}
              placeholder="内容质量"
              onChange={(event) => onChange({ dimensionName: event.target.value })}
            />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">权重</label>
            <Input
              type="number"
              value={item.weight}
              disabled={!editable}
              onChange={(event) => onChange({ weight: Number(event.target.value) || 0 })}
            />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">排序</label>
            <Input
              type="number"
              value={item.sortNo}
              disabled={!editable}
              onChange={(event) => onChange({ sortNo: Number(event.target.value) || 0 })}
            />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">最低分</label>
            <Input
              type="number"
              value={item.scoreMin}
              disabled={!editable}
              onChange={(event) => onChange({ scoreMin: Number(event.target.value) || 0 })}
            />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">最高分</label>
            <Input
              type="number"
              value={item.scoreMax}
              disabled={!editable}
              onChange={(event) => onChange({ scoreMax: Number(event.target.value) || 0 })}
            />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">通过阈值</label>
            <Input
              type="number"
              value={item.passThreshold ?? ""}
              disabled={!editable}
              onChange={(event) =>
                onChange({
                  passThreshold: event.target.value === "" ? null : Number(event.target.value),
                })
              }
            />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-medium text-muted-foreground">驳回阈值</label>
            <Input
              type="number"
              value={item.rejectThreshold ?? ""}
              disabled={!editable}
              onChange={(event) =>
                onChange({
                  rejectThreshold: event.target.value === "" ? null : Number(event.target.value),
                })
              }
            />
          </div>
        </div>
        <div className="mt-4 space-y-1.5">
          <label className="text-xs font-medium text-muted-foreground">维度审核说明</label>
          <Textarea
            value={item.promptInstruction ?? ""}
            disabled={!editable}
            rows={4}
            placeholder="描述该维度如何评判，例如：检查标注是否覆盖题面要求的全部字段"
            onChange={(event) => onChange({ promptInstruction: event.target.value })}
          />
          {proMode ? (
            <p className="text-[11px] leading-4 text-muted-foreground">
              专业模式插槽：{`{{dimension.${item.dimensionName || "维度名称"}.prompt_instruction}}`}
            </p>
          ) : (
            <p className="text-[11px] leading-4 text-muted-foreground">
              保存后将自动写入 Prompt 的 [{item.dimensionName || "维度名称"}] 段落，无需手动编辑模板变量。
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

export function TemplateReviewConfigPanel({ versionId, editable, onSaved, onCancel }: TemplateReviewConfigPanelProps) {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [importing, setImporting] = useState(false);
  const [loadingPacks, setLoadingPacks] = useState(false);
  const [mode, setMode] = useState<ReviewConfigMode>("standard");
  const [promptTemplate, setPromptTemplate] = useState("");
  const [draftItems, setDraftItems] = useState<ReviewDimensionItem[]>([]);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [packOptions, setPackOptions] = useState<DimensionPackOption[]>([]);
  const [selectedPackId, setSelectedPackId] = useState("");
  const [packSearch, setPackSearch] = useState("");
  const [reviewDirty, setReviewDirty] = useState(false);
  const [llmCatalog, setLlmCatalog] = useState<LlmCatalogProviderOption[]>([]);
  const [loadingCatalog, setLoadingCatalog] = useState(false);
  const [providerPlatformKey, setProviderPlatformKey] = useState("");
  const [modelId, setModelId] = useState("");
  const [workflowLevels, setWorkflowLevels] = useState<ReviewWorkflowLevelItem[]>(DEFAULT_REVIEW_WORKFLOW_LEVELS);
  const [assistLoadingMode, setAssistLoadingMode] = useState<ReviewPromptAssistMode | null>(null);
  const [assistResult, setAssistResult] = useState<ReviewPromptAssistResult | null>(null);

  const markReviewDirty = () => setReviewDirty(true);

  const providerOptions = useMemo<ComboboxOption[]>(
    () =>
      llmCatalog.map((provider) => ({
        value: provider.providerCode,
        label: provider.providerName,
      })),
    [llmCatalog],
  );

  const modelOptions = useMemo<ComboboxOption[]>(() => {
    const provider = llmCatalog.find((item) => item.providerCode === providerPlatformKey);
    if (!provider) {
      return [];
    }
    return provider.models.map((model) => ({
      value: model.modelCode,
      label: `${model.modelName} (${model.modelCode})`,
    }));
  }, [llmCatalog, providerPlatformKey]);

  const packComboboxOptions = useMemo<ComboboxOption[]>(() => {
    const keyword = packSearch.trim().toLowerCase();
    return packOptions
      .filter((option) => {
        if (!keyword) {
          return true;
        }
        return (
          option.packName.toLowerCase().includes(keyword) ||
          option.packCode.toLowerCase().includes(keyword)
        );
      })
      .map((option) => ({
        value: String(option.id),
        label: `${option.packName} (${option.packCode})`,
      }));
  }, [packOptions, packSearch]);

  const totalWeight = useMemo(() => sumReviewDimensionWeights(draftItems), [draftItems]);
  const weightValid = draftItems.length === 0 || Math.abs(totalWeight - 100) <= 0.01;
  const selectedItem = draftItems[selectedIndex];

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    void fetchReviewConfig(versionId)
      .then((config) => {
        if (cancelled) {
          return;
        }
        const items = config.dimensions.map((item) => ({ ...item }));
        const storedPrompt = config.reviewPromptTemplate?.trim() ?? "";
        setDraftItems(items);
        setPromptTemplate(storedPrompt || buildReviewPromptFromDimensions(items));
        setMode(isAutoGeneratedReviewPrompt(storedPrompt, items) ? "standard" : "pro");
        setProviderPlatformKey(config.providerPlatformKey ?? "");
        setModelId(config.modelId ?? "");
        setWorkflowLevels(config.reviewWorkflowLevels.map((level) => ({ ...level, actions: [...level.actions] })));
        setAssistResult(null);
        setSelectedIndex(0);
        setReviewDirty(false);
      })
      .catch((error: unknown) => {
        if (!cancelled) {
          appMessage.errorUnlessHandled("加载审核配置失败", error);
        }
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });
    return () => {
      cancelled = true;
    };
  }, [versionId]);

  useEffect(() => {
    setLoadingCatalog(true);
    void fetchLlmCatalog("REVIEW")
      .then(setLlmCatalog)
      .catch((error: unknown) => appMessage.errorUnlessHandled("加载 LLM 目录失败", error))
      .finally(() => setLoadingCatalog(false));
  }, []);

  useEffect(() => {
    setLoadingPacks(true);
    void listDimensionPackOptions()
      .then(setPackOptions)
      .catch((error: unknown) => appMessage.errorUnlessHandled("加载维度包列表失败", error))
      .finally(() => setLoadingPacks(false));
  }, []);

  useEffect(() => {
    if (selectedIndex >= draftItems.length) {
      setSelectedIndex(Math.max(0, draftItems.length - 1));
    }
  }, [draftItems.length, selectedIndex]);

  useEffect(() => {
    if (loading) {
      return;
    }
    const store = useDesignerReviewConfigStore.getState();
    store.bindDraft(
      versionId,
      () => ({ mode, promptTemplate, draftItems }),
      reviewDirty,
    );
    return () => store.unbindDraft(versionId);
  }, [versionId, loading, mode, promptTemplate, draftItems, reviewDirty]);

  const handleAdd = () => {
    markReviewDirty();
    setDraftItems((items) => {
      const next = [...items, createEmptyReviewDimension(items.length + 1)];
      setSelectedIndex(next.length - 1);
      return next;
    });
  };

  const handleRemove = (index: number) => {
    markReviewDirty();
    setDraftItems((items) => items.filter((_, itemIndex) => itemIndex !== index));
    setSelectedIndex((current) => {
      if (current > index) return current - 1;
      if (current === index) return Math.max(0, index - 1);
      return current;
    });
  };

  const handleImport = async () => {
    if (!selectedPackId) {
      toast.error("请选择维度包");
      return;
    }
    setImporting(true);
    try {
      const imported = await applyDimensionPack(versionId, Number(selectedPackId));
      setDraftItems(imported.map((item) => ({ ...item })));
      setSelectedIndex(0);
      if (mode === "standard") {
        setPromptTemplate(buildReviewPromptFromDimensions(imported));
      }
      setReviewDirty(false);
      useDesignerReviewConfigStore.getState().markClean(versionId);
      toast.success("已从维度包导入审核维度");
    } catch {
      toast.error("导入维度包失败");
    } finally {
      setImporting(false);
    }
  };

  const handleSave = async () => {
    if (!editable) {
      toast.error("仅草稿版本可编辑审核配置");
      return;
    }
    const validationError = validateReviewDimensions(draftItems);
    if (validationError) {
      toast.error(validationError);
      return;
    }
    const workflowError = validateReviewWorkflowLevels(workflowLevels);
    if (workflowError) {
      toast.error(workflowError);
      return;
    }
    if (!providerPlatformKey.trim() || !modelId.trim()) {
      toast.error("请选择 AI 预审 Provider 与 Model");
      return;
    }
    setSaving(true);
    try {
      const payload = toReviewDimensionPayload(draftItems);
      const finalPrompt =
        mode === "standard" ? buildReviewPromptFromDimensions(payload) : promptTemplate.trim();
      const saved = await saveReviewConfig(versionId, finalPrompt, payload, {
        providerPlatformKey: providerPlatformKey.trim(),
        modelId: modelId.trim(),
        reviewWorkflowLevels: workflowLevels,
      });
      const savedItems = saved.dimensions.map((item) => ({ ...item }));
      const savedPrompt = saved.reviewPromptTemplate?.trim() ?? finalPrompt;
      setDraftItems(savedItems);
      setPromptTemplate(savedPrompt);
      setMode(isAutoGeneratedReviewPrompt(savedPrompt, savedItems) ? "standard" : "pro");
      setProviderPlatformKey(saved.providerPlatformKey ?? providerPlatformKey);
      setModelId(saved.modelId ?? modelId);
      setWorkflowLevels(saved.reviewWorkflowLevels.map((level) => ({ ...level, actions: [...level.actions] })));
      setReviewDirty(false);
      useDesignerReviewConfigStore.getState().markClean(versionId);
      toast.success("审核配置已保存");
      onSaved?.();
    } catch (error) {
      appMessage.errorUnlessHandled("保存审核配置失败", error);
    } finally {
      setSaving(false);
    }
  };

  const handleGenerateAssist = async (modeValue: ReviewPromptAssistMode) => {
    if (!editable) {
      toast.error("仅草稿版本可使用 AI 辅助");
      return;
    }
    const validationError = validateReviewDimensions(draftItems);
    if (validationError) {
      toast.error(validationError);
      return;
    }
    if (!providerPlatformKey.trim() || !modelId.trim()) {
      toast.error("请先选择 AI 预审 Provider 与 Model");
      return;
    }
    const payload = toReviewDimensionPayload(draftItems);
    const currentPrompt =
      mode === "standard" ? buildReviewPromptFromDimensions(payload) : promptTemplate.trim();
    setAssistLoadingMode(modeValue);
    try {
      const suggestion = await generateReviewPromptAssist(versionId, {
        mode: modeValue,
        providerPlatformKey: providerPlatformKey.trim(),
        modelId: modelId.trim(),
        currentPromptTemplate: currentPrompt,
        dimensions: payload,
      });
      setAssistResult(suggestion);
      toast.success(modeValue === "INITIAL_DRAFT" ? "已生成通用初稿建议" : "已生成基于历史的优化建议");
    } catch {
      // 请求错误由 apiClient 统一 toast，避免与 catch 重复提示。
    } finally {
      setAssistLoadingMode(null);
    }
  };

  const handleApplyAssist = () => {
    if (!assistResult?.suggestedPromptTemplate) {
      return;
    }
    markReviewDirty();
    setMode("pro");
    setPromptTemplate(assistResult.suggestedPromptTemplate);
    toast.success("已应用 AI 建议，请检查后保存");
  };

  if (loading) {
    return <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground">正在加载审核配置…</div>;
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
      <div className="min-h-0 flex-1 overflow-y-auto">
      <section className="border-b border-border px-6 py-4">
        <div className="mb-3">
          <h2 className="text-sm font-semibold text-foreground">AI 预审模型</h2>
          <p className="mt-0.5 text-xs text-muted-foreground">从平台目录选择 Provider 与 Model，发布任务后将随模板版本冻结</p>
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-1.5">
            <Label>Provider</Label>
            <Combobox
              value={providerPlatformKey}
              options={providerOptions}
              disabled={!editable || loadingCatalog}
              placeholder={loadingCatalog ? "加载目录…" : "选择 LLM 提供商"}
              onValueChange={(value) => {
                markReviewDirty();
                setProviderPlatformKey(value);
                setModelId("");
              }}
            />
          </div>
          <div className="space-y-1.5">
            <Label>Model</Label>
            <Combobox
              value={modelId}
              options={modelOptions}
              disabled={!editable || !providerPlatformKey || loadingCatalog}
              placeholder={providerPlatformKey ? "选择模型" : "请先选择 Provider"}
              onValueChange={(value) => {
                markReviewDirty();
                setModelId(value);
              }}
            />
          </div>
        </div>
      </section>
      <section className="border-b border-border px-6 py-4">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="max-w-2xl">
            <h2 className="text-sm font-semibold text-foreground">AI 辅助提示词</h2>
            <p className="mt-0.5 text-xs text-muted-foreground">
              发布前可先生成通用初稿；运行后可在<strong className="font-medium text-foreground">新草稿版本</strong>
              上基于同模板已发布版本的 AI 预审与人工复核样本优化 Prompt。
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              disabled={!editable || assistLoadingMode !== null}
              onClick={() => void handleGenerateAssist("INITIAL_DRAFT")}
            >
              {assistLoadingMode === "INITIAL_DRAFT" ? "生成中…" : "生成通用初稿"}
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              disabled={!editable || assistLoadingMode !== null}
              onClick={() => void handleGenerateAssist("OPTIMIZE_FROM_HISTORY")}
            >
              {assistLoadingMode === "OPTIMIZE_FROM_HISTORY" ? "优化中…" : "基于历史优化"}
            </Button>
          </div>
        </div>
        {assistResult ? (
          <div className="mt-4 rounded-xl border border-border bg-muted/40 p-4">
            <div className="flex flex-wrap items-start justify-between gap-3">
              <div className="space-y-1">
                <p className="text-sm font-medium text-foreground">
                  {assistResult.usedHistory
                    ? `已参考 ${assistResult.historyCaseCount} 条历史复核样本`
                    : "当前建议基于模板通用信息生成"}
                </p>
                <p className="text-xs text-muted-foreground">{assistResult.summary || "AI 已返回新的审核提示词建议"}</p>
              </div>
              <Button type="button" size="sm" onClick={handleApplyAssist}>
                应用到 Prompt
              </Button>
            </div>
            {assistResult.focusPoints.length > 0 ? (
              <div className="mt-3 flex flex-wrap gap-2">
                {assistResult.focusPoints.map((point) => (
                  <span
                    key={point}
                    className="rounded-full border border-border bg-background px-2.5 py-1 text-[11px] text-muted-foreground"
                  >
                    {point}
                  </span>
                ))}
              </div>
            ) : null}
          </div>
        ) : null}
      </section>
      <section className="border-b border-border px-6 py-4">
        <ReviewWorkflowEditor
          levels={workflowLevels}
          editable={editable}
          onChange={(levels) => {
            markReviewDirty();
            setWorkflowLevels(levels);
          }}
        />
      </section>
      <section className="border-b border-border px-6 py-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-sm font-semibold text-foreground">配置模式</h2>
            <p className="mt-0.5 text-xs text-muted-foreground">
              标准模式只需配置维度；维度插槽与题目数据变量由系统自动组装
            </p>
          </div>
          <div className="inline-flex rounded-lg border border-border p-0.5">
            <button
              type="button"
              disabled={!editable}
              className={cn(
                "rounded-md px-3 py-1.5 text-xs font-medium transition",
                mode === "standard"
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground",
              )}
              onClick={() => {
                markReviewDirty();
                setMode("standard");
              }}
            >
              标准配置
            </button>
            <button
              type="button"
              disabled={!editable}
              className={cn(
                "rounded-md px-3 py-1.5 text-xs font-medium transition",
                mode === "pro"
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground",
              )}
              onClick={() => {
                markReviewDirty();
                setMode("pro");
              }}
            >
              专业模式
            </button>
          </div>
        </div>
      </section>

      {mode === "standard" ? (
        <section className="border-b border-border bg-muted/60 px-6 py-3">
          <p className="text-xs text-muted-foreground">
            维度插槽、原始题目与用户提交数据会在保存时<strong>自动写入</strong> Prompt，无需手动编辑模板。
          </p>
          {draftItems.length > 0 ? (
            <p className="mt-2 text-xs text-muted-foreground">
              将包含维度：
              {draftItems.map((item, index) => dimensionCardTitle(item, index)).join("、")}
            </p>
          ) : (
            <p className="mt-2 text-xs text-muted-foreground">请先添加或导入审核维度</p>
          )}
        </section>
      ) : (
        <ReviewPromptProEditor
          value={promptTemplate}
          editable={editable}
          dimensions={draftItems}
          onChange={(value) => {
            markReviewDirty();
            setPromptTemplate(value);
          }}
        />
      )}

      <section className="border-b border-border px-6 py-3">
        <div className="flex flex-wrap items-end gap-2">
          <div className="min-w-[220px] flex-1">
            <Label className="mb-1 block text-xs font-medium text-muted-foreground">从维度包导入</Label>
            <Combobox
              value={selectedPackId}
              onValueChange={setSelectedPackId}
              options={packComboboxOptions}
              placeholder={loadingPacks ? "加载中…" : "搜索或选择维度包"}
              disabled={!editable || loadingPacks || importing}
              searchValue={packSearch}
              onSearchChange={setPackSearch}
              shouldFilter={false}
              emptyText="未找到匹配的维度包"
              className="h-9 rounded-md py-1.5"
            />
          </div>
          <Button
            type="button"
            variant="outline"
            size="sm"
            disabled={!editable || !selectedPackId || importing}
            onClick={() => void handleImport()}
          >
            {importing ? "导入中…" : "导入"}
          </Button>
          <Button type="button" variant="outline" size="sm" disabled={!editable} onClick={handleAdd}>
            <Plus className="mr-1.5 h-4 w-4" />
            新增维度
          </Button>
        </div>
        <div className="mt-2 text-xs text-muted-foreground">
          权重合计：
          <span className={cn("font-medium", weightValid ? "text-emerald-600" : "text-red-600")}>
            {totalWeight.toFixed(2)}
          </span>
          / 100 · 共 {draftItems.length} 项
        </div>
      </section>

      <div className="grid min-h-[min(420px,45vh)] grid-cols-[240px_minmax(0,1fr)] border-t border-border">
        <aside className="flex min-h-0 flex-col border-r border-border bg-muted/70">
          <div className="border-b border-border px-3 py-2 text-xs font-medium text-muted-foreground">
            审核维度
          </div>
          <div className="min-h-0 flex-1 overflow-auto p-2">
            {draftItems.length === 0 ? (
              <p className="px-2 py-6 text-center text-xs text-muted-foreground">暂无维度</p>
            ) : (
              <ul className="space-y-2">
                {draftItems.map((item, index) => {
                  const active = index === selectedIndex;
                  return (
                    <li key={`${item.dimensionKey}-${index}`}>
                      <button
                        type="button"
                        className={cn(
                          "w-full rounded-lg border px-3 py-2.5 text-left transition",
                          active
                            ? "border-primary/30 bg-card shadow-sm"
                            : "border-transparent hover:border-border hover:bg-card/80",
                        )}
                        onClick={() => setSelectedIndex(index)}
                      >
                        <div className="flex items-start justify-between gap-2">
                          <span className="line-clamp-1 text-sm font-medium text-foreground">
                            {dimensionCardTitle(item, index)}
                          </span>
                          <span className="shrink-0 rounded bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">
                            {item.weight}
                          </span>
                        </div>
                        <p className="mt-1 line-clamp-1 text-[11px] text-muted-foreground">{item.dimensionKey || "未设置编码"}</p>
                      </button>
                    </li>
                  );
                })}
              </ul>
            )}
          </div>
        </aside>
        <section className="min-h-0 bg-card">
          {selectedItem ? (
            <ReviewDimensionEditorPanel
              item={selectedItem}
              index={selectedIndex}
              editable={editable}
              proMode={mode === "pro"}
              onChange={(patch) => {
                markReviewDirty();
                setDraftItems((items) => patchDimension(items, selectedIndex, patch));
              }}
              onRemove={() => handleRemove(selectedIndex)}
            />
          ) : (
            <div className="flex h-full items-center justify-center p-8 text-center text-sm text-muted-foreground">
              暂无审核维度，可从维度包导入或手动新增
            </div>
          )}
        </section>
      </div>
      </div>

      <div className="flex shrink-0 items-center justify-end gap-2 border-t border-border px-6 py-3">
        {onCancel ? (
          <Button type="button" variant="outline" onClick={onCancel}>
            取消
          </Button>
        ) : null}
        <Button type="button" disabled={!editable || saving} onClick={() => void handleSave()}>
          {saving ? "保存中…" : "保存审核配置"}
        </Button>
      </div>
    </div>
  );
}
