CREATE TABLE submission_appeals (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    submission_id BIGINT NOT NULL,
    assignment_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    labeler_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    appeal_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    reason_text VARCHAR(1000) NULL,
    decision_reason_text VARCHAR(1000) NULL,
    decided_by BIGINT NULL,
    decided_at TIMESTAMP NULL DEFAULT NULL,
    batch_key VARCHAR(128) NULL,
    ext_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_submission_appeals_submission_no (submission_id, appeal_no),
    KEY idx_submission_appeals_owner_status_deleted (tenant_id, owner_id, status, deleted_flag),
    KEY idx_submission_appeals_labeler_deleted (tenant_id, labeler_id, deleted_flag),
    KEY idx_submission_appeals_task_deleted (tenant_id, task_id, deleted_flag)
);

CREATE TABLE appeal_batch_operations (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    batch_key VARCHAR(128) NOT NULL,
    task_id BIGINT NULL,
    operator_id BIGINT NOT NULL,
    batch_action VARCHAR(64) NOT NULL,
    criteria_json JSON NULL,
    target_total_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NULL DEFAULT NULL,
    finished_at TIMESTAMP NULL DEFAULT NULL,
    failure_summary_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_appeal_batch_operations_batch_key (batch_key),
    KEY idx_appeal_batch_operations_operator_status_deleted (tenant_id, operator_id, status, deleted_flag)
);
