CREATE TABLE ai_review_prompt_suggestions (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    template_version_id BIGINT NOT NULL,
    task_id BIGINT NULL,
    owner_id BIGINT NOT NULL,
    baseline_prompt_template MEDIUMTEXT NOT NULL,
    candidate_prompt_template MEDIUMTEXT NOT NULL,
    change_summary TEXT NULL,
    baseline_metrics_json JSON NULL,
    ab_test_report_json JSON NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    decided_by BIGINT NULL,
    decided_at TIMESTAMP NULL,
    dismiss_reason VARCHAR(500) NULL,
    accepted_template_version_id BIGINT NULL,
    cooldown_until TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_suggestions_owner_status (tenant_id, owner_id, status, created_at DESC),
    KEY idx_suggestions_template (tenant_id, template_version_id, status)
);
