import type { ReviewDimensionItem } from "@/features/template-designer/types/review-dimension";

export const REVIEW_PROMPT_INTRO =
  "你是 LabelHub 审核 Agent。请基于以下维度为提交内容打分（0-100）：";

export const REVIEW_PROMPT_DATA_SUFFIX = `---
原始题目数据：
{{original_item_data}}

---
用户标注提交的结果：
{{user_submission_data}}

请通过 function_call 返回严格 JSON，不要输出多余说明。`;

export function buildDimensionSlotLine(dimensionName: string): string {
  const name = dimensionName.trim();
  if (!name) {
    return "";
  }
  return `[${name}] {{dimension.${name}.prompt_instruction}}`;
}

/** 根据审核维度自动生成完整 review_prompt_template */
export function buildReviewPromptFromDimensions(dimensions: ReviewDimensionItem[]): string {
  const slotLines = dimensions
    .map((item) => buildDimensionSlotLine(item.dimensionName))
    .filter(Boolean);
  const dimensionBlock = slotLines.length > 0 ? `\n${slotLines.join("\n")}\n` : "\n";
  return `${REVIEW_PROMPT_INTRO}${dimensionBlock}\n${REVIEW_PROMPT_DATA_SUFFIX}`;
}

function normalizePrompt(text: string): string {
  return text.replace(/\r\n/g, "\n").trim();
}

/** 判断已存 Prompt 是否为系统自动生成的结构（用于恢复「标准模式」） */
export function isAutoGeneratedReviewPrompt(
  template: string | null | undefined,
  dimensions: ReviewDimensionItem[],
): boolean {
  if (!template?.trim()) {
    return true;
  }
  const built = buildReviewPromptFromDimensions(dimensions);
  return normalizePrompt(template) === normalizePrompt(built);
}

export const DEFAULT_REVIEW_PROMPT_TEMPLATE = buildReviewPromptFromDimensions([
  {
    dimensionKey: "COMPLETENESS",
    dimensionName: "完整性",
    weight: 25,
    scoreMin: 0,
    scoreMax: 100,
    severityLevel: "MEDIUM",
    sortNo: 1,
    requiredFlag: 1,
  },
  {
    dimensionKey: "ACCURACY",
    dimensionName: "准确性",
    weight: 25,
    scoreMin: 0,
    scoreMax: 100,
    severityLevel: "MEDIUM",
    sortNo: 2,
    requiredFlag: 1,
  },
  {
    dimensionKey: "FORMAT",
    dimensionName: "格式合规",
    weight: 25,
    scoreMin: 0,
    scoreMax: 100,
    severityLevel: "MEDIUM",
    sortNo: 3,
    requiredFlag: 1,
  },
  {
    dimensionKey: "SAFETY",
    dimensionName: "安全性",
    weight: 25,
    scoreMin: 0,
    scoreMax: 100,
    severityLevel: "MEDIUM",
    sortNo: 4,
    requiredFlag: 1,
  },
]);
