#!/usr/bin/env python3
"""Generate LabelHub DDL from docs/database-design.md conventions."""

from pathlib import Path

BASE = """  `id` BIGINT UNSIGNED NOT NULL,
  `tenant_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `ext_json` JSON NULL"""


def create_table(name: str, cols: list[str], uks: list[tuple[str, str]] | None = None, idxs: list[tuple[str, str]] | None = None) -> str:
    parts = [f"CREATE TABLE `{name}` (", BASE + ","]
    parts.extend(f"  {c}," for c in cols)
    parts.append("  PRIMARY KEY (`id`)")
    keys: list[str] = []
    if uks:
        keys.extend(f"  UNIQUE KEY `{n}` ({c})" for n, c in uks)
    if idxs:
        keys.extend(f"  KEY `{n}` ({c})" for n, c in idxs)
    if keys:
        parts[-1] += ","
        parts.extend(k + ("," if i < len(keys) - 1 else "") for i, k in enumerate(keys))
    parts.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;")
    return "\n".join(parts)


TABLES: list[tuple] = [
    # 8.1 identity
    ("users", [
        "`username` VARCHAR(64) NOT NULL",
        "`password_hash` VARCHAR(255) NOT NULL",
        "`display_name` VARCHAR(64) NOT NULL",
        "`email` VARCHAR(128) NULL",
        "`phone` VARCHAR(32) NULL",
        "`avatar_file_id` BIGINT UNSIGNED NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
        "`last_login_at` DATETIME(3) NULL",
        "`register_source` VARCHAR(32) NOT NULL DEFAULT 'WEB'",
    ], [("uk_users_tenant_username", "`tenant_id`, `username`, `deleted_flag`")],
       [("idx_users_status", "`tenant_id`, `status`, `id`"), ("idx_users_last_login", "`tenant_id`, `last_login_at`")]),
    ("roles", [
        "`role_code` VARCHAR(32) NOT NULL",
        "`role_name` VARCHAR(64) NOT NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
        "`remark` VARCHAR(255) NULL",
    ], [("uk_roles_tenant_code", "`tenant_id`, `role_code`, `deleted_flag`")],
       [("idx_roles_status", "`tenant_id`, `status`")]),
    ("permissions", [
        "`permission_code` VARCHAR(64) NOT NULL",
        "`permission_name` VARCHAR(128) NOT NULL",
        "`module_code` VARCHAR(32) NOT NULL",
        "`api_pattern` VARCHAR(255) NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
    ], [("uk_permissions_tenant_code", "`tenant_id`, `permission_code`, `deleted_flag`")],
       [("idx_permissions_module", "`tenant_id`, `module_code`, `status`")]),
    ("role_permissions", [
        "`role_id` BIGINT UNSIGNED NOT NULL",
        "`permission_id` BIGINT UNSIGNED NOT NULL",
        "`grant_source` VARCHAR(32) NOT NULL DEFAULT 'SYSTEM'",
    ], [("uk_role_permissions", "`tenant_id`, `role_id`, `permission_id`, `deleted_flag`")],
       [("idx_role_permissions_perm", "`tenant_id`, `permission_id`, `role_id`")]),
    ("user_roles", [
        "`user_id` BIGINT UNSIGNED NOT NULL",
        "`role_id` BIGINT UNSIGNED NOT NULL",
        "`effective_at` DATETIME(3) NULL",
        "`expired_at` DATETIME(3) NULL",
    ], [("uk_user_roles", "`tenant_id`, `user_id`, `role_id`, `deleted_flag`")],
       [("idx_user_roles_role", "`tenant_id`, `role_id`, `user_id`")]),
    ("sys_menus", [
        "`menu_code` VARCHAR(64) NOT NULL",
        "`menu_name` VARCHAR(128) NOT NULL",
        "`menu_type` VARCHAR(16) NOT NULL",
        "`parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0",
        "`path` VARCHAR(255) NULL",
        "`route_name` VARCHAR(128) NULL",
        "`component_path` VARCHAR(255) NULL",
        "`redirect_path` VARCHAR(255) NULL",
        "`icon` VARCHAR(128) NULL",
        "`permission_code` VARCHAR(64) NULL",
        "`visible_flag` TINYINT UNSIGNED NOT NULL DEFAULT 1",
        "`disabled_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`cache_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`affix_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`external_link_url` VARCHAR(255) NULL",
        "`open_mode` VARCHAR(16) NOT NULL DEFAULT 'INTERNAL'",
        "`sort_no` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
    ], [("uk_sys_menus_code", "`tenant_id`, `menu_code`, `deleted_flag`")],
       [("idx_sys_menus_parent_sort", "`tenant_id`, `parent_id`, `sort_no`, `id`"),
        ("idx_sys_menus_route", "`tenant_id`, `path`, `route_name`"),
        ("idx_sys_menus_status_visible", "`tenant_id`, `status`, `visible_flag`, `disabled_flag`")]),
    ("role_menus", [
        "`role_id` BIGINT UNSIGNED NOT NULL",
        "`menu_id` BIGINT UNSIGNED NOT NULL",
        "`grant_scope` VARCHAR(16) NOT NULL DEFAULT 'VISIBLE'",
    ], [("uk_role_menus", "`tenant_id`, `role_id`, `menu_id`, `deleted_flag`")],
       [("idx_role_menus_menu", "`tenant_id`, `menu_id`, `role_id`"),
        ("idx_role_menus_role", "`tenant_id`, `role_id`, `menu_id`")]),
    ("auth_sessions", [
        "`user_id` BIGINT UNSIGNED NOT NULL",
        "`login_type` VARCHAR(16) NOT NULL DEFAULT 'PASSWORD'",
        "`client_type` VARCHAR(16) NOT NULL DEFAULT 'WEB'",
        "`access_jti` VARCHAR(128) NOT NULL",
        "`access_token_hash` CHAR(64) NOT NULL",
        "`device_id` VARCHAR(128) NULL",
        "`device_name` VARCHAR(128) NULL",
        "`ip_address` VARCHAR(64) NULL",
        "`user_agent` VARCHAR(512) NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
        "`issued_at` DATETIME(3) NOT NULL",
        "`access_expires_at` DATETIME(3) NOT NULL",
        "`refresh_expires_at` DATETIME(3) NULL",
        "`last_seen_at` DATETIME(3) NULL",
        "`logout_at` DATETIME(3) NULL",
        "`revoked_at` DATETIME(3) NULL",
        "`revoke_reason` VARCHAR(255) NULL",
    ], [("uk_auth_sessions_jti", "`tenant_id`, `access_jti`, `deleted_flag`")],
       [("idx_auth_sessions_user_status", "`tenant_id`, `user_id`, `status`, `issued_at`"),
        ("idx_auth_sessions_expire", "`tenant_id`, `status`, `access_expires_at`")]),
    ("auth_refresh_tokens", [
        "`session_id` BIGINT UNSIGNED NOT NULL",
        "`user_id` BIGINT UNSIGNED NOT NULL",
        "`refresh_token_hash` CHAR(64) NOT NULL",
        "`rotate_no` INT UNSIGNED NOT NULL DEFAULT 1",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
        "`issued_at` DATETIME(3) NOT NULL",
        "`expires_at` DATETIME(3) NOT NULL",
        "`used_at` DATETIME(3) NULL",
        "`revoked_at` DATETIME(3) NULL",
        "`replaced_by_token_id` BIGINT UNSIGNED NULL",
        "`revoke_reason` VARCHAR(255) NULL",
    ], [("uk_auth_refresh_tokens_hash", "`tenant_id`, `refresh_token_hash`, `deleted_flag`"),
        ("uk_auth_refresh_tokens_rotate", "`tenant_id`, `session_id`, `rotate_no`, `deleted_flag`")],
       [("idx_auth_refresh_tokens_user_status", "`tenant_id`, `user_id`, `status`, `expires_at`"),
        ("idx_auth_refresh_tokens_session", "`tenant_id`, `session_id`, `rotate_no`")]),
    ("system_clients", [
        "`client_code` VARCHAR(64) NOT NULL",
        "`client_name` VARCHAR(128) NOT NULL",
        "`client_secret_hash` VARCHAR(255) NOT NULL",
        "`client_type` VARCHAR(32) NOT NULL",
        "`allowed_scopes_json` JSON NOT NULL",
        "`ip_whitelist_json` JSON NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
        "`last_used_at` DATETIME(3) NULL",
        "`expires_at` DATETIME(3) NULL",
    ], [("uk_system_clients_code", "`tenant_id`, `client_code`, `deleted_flag`")],
       [("idx_system_clients_status", "`tenant_id`, `status`, `expires_at`")]),
    ("sys_dict_types", [
        "`dict_code` VARCHAR(64) NOT NULL",
        "`dict_name` VARCHAR(128) NOT NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
        "`remark` VARCHAR(255) NULL",
    ], [("uk_sys_dict_types_code", "`tenant_id`, `dict_code`, `deleted_flag`")],
       [("idx_sys_dict_types_status", "`tenant_id`, `status`")]),
    ("sys_dict_items", [
        "`dict_type_id` BIGINT UNSIGNED NOT NULL",
        "`item_code` VARCHAR(64) NOT NULL",
        "`item_label` VARCHAR(128) NOT NULL",
        "`item_value` VARCHAR(256) NOT NULL",
        "`sort_no` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`is_default` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
    ], [("uk_sys_dict_items_code", "`tenant_id`, `dict_type_id`, `item_code`, `deleted_flag`")],
       [("idx_sys_dict_items_sort", "`tenant_id`, `dict_type_id`, `status`, `sort_no`")]),
    ("plugin_registry", [
        "`plugin_code` VARCHAR(64) NOT NULL",
        "`plugin_name` VARCHAR(128) NOT NULL",
        "`plugin_type` VARCHAR(32) NOT NULL",
        "`plugin_version` VARCHAR(32) NOT NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'INSTALLED'",
        "`entry_class` VARCHAR(255) NULL",
        "`supported_extensions_json` JSON NOT NULL",
        "`config_json` JSON NULL",
        "`installed_at` DATETIME(3) NULL",
        "`enabled_at` DATETIME(3) NULL",
        "`last_health_check_at` DATETIME(3) NULL",
    ], [("uk_plugin_registry_code", "`tenant_id`, `plugin_code`, `deleted_flag`")],
       [("idx_plugin_registry_type", "`tenant_id`, `plugin_type`, `status`")]),
    ("plg_agent_provider_configs", [
        "`platform_key` VARCHAR(64) NOT NULL",
        "`platform_name` VARCHAR(128) NOT NULL",
        "`base_url` VARCHAR(255) NOT NULL",
        "`api_key_ciphertext` VARCHAR(1024) NOT NULL",
        "`default_model` VARCHAR(128) NULL",
        "`supported_models_json` JSON NULL",
        "`usage_scenarios_json` JSON NULL",
        "`extra_config_json` JSON NULL",
        "`is_default` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
        "`last_health_status` VARCHAR(16) NULL",
        "`last_health_check_at` DATETIME(3) NULL",
        "`last_error_message` VARCHAR(512) NULL",
    ], [("uk_plg_agent_provider_configs_key", "`tenant_id`, `platform_key`, `deleted_flag`")],
       [("idx_plg_agent_provider_configs_status", "`tenant_id`, `status`, `is_default`"),
        ("idx_plg_agent_provider_configs_health", "`tenant_id`, `last_health_status`, `last_health_check_at`")]),
    # 8.2 runtime
    ("async_tasks", [
        "`task_type` VARCHAR(32) NOT NULL",
        "`biz_type` VARCHAR(32) NOT NULL",
        "`biz_id` BIGINT UNSIGNED NOT NULL",
        "`biz_key` VARCHAR(128) NOT NULL",
        "`priority` TINYINT UNSIGNED NOT NULL DEFAULT 5",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`payload_json` JSON NOT NULL",
        "`retry_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`max_retry_count` SMALLINT UNSIGNED NOT NULL DEFAULT 3",
        "`manual_retry_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`next_run_at` DATETIME(3) NULL",
        "`worker_id` VARCHAR(64) NULL",
        "`locked_at` DATETIME(3) NULL",
        "`started_at` DATETIME(3) NULL",
        "`finished_at` DATETIME(3) NULL",
        "`canceled_at` DATETIME(3) NULL",
        "`dead_lettered_at` DATETIME(3) NULL",
        "`last_error_code` VARCHAR(64) NULL",
        "`last_error_message` VARCHAR(512) NULL",
    ], [("uk_async_tasks_biz", "`tenant_id`, `task_type`, `biz_key`, `deleted_flag`")],
       [("idx_async_tasks_status_run", "`tenant_id`, `status`, `next_run_at`, `priority`, `id`"),
        ("idx_async_tasks_biz", "`tenant_id`, `biz_type`, `biz_id`, `status`"),
        ("idx_async_tasks_worker", "`tenant_id`, `worker_id`, `status`")]),
    ("audit_logs", [
        "`entity_type` VARCHAR(32) NOT NULL",
        "`entity_id` BIGINT UNSIGNED NOT NULL",
        "`action_code` VARCHAR(64) NOT NULL",
        "`operator_type` VARCHAR(16) NOT NULL DEFAULT 'USER'",
        "`operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0",
        "`operator_name` VARCHAR(64) NULL",
        "`request_id` VARCHAR(64) NULL",
        "`trace_id` VARCHAR(64) NULL",
        "`source_ip` VARCHAR(64) NULL",
        "`before_json` JSON NULL",
        "`after_json` JSON NULL",
        "`diff_json` JSON NULL",
        "`remark` VARCHAR(512) NULL",
        "`idempotency_key` VARCHAR(128) NULL",
        "`occurred_at` DATETIME(3) NOT NULL",
    ], [("uk_audit_logs_idem", "`tenant_id`, `entity_type`, `entity_id`, `action_code`, `idempotency_key`, `deleted_flag`")],
       [("idx_audit_logs_entity_time", "`tenant_id`, `entity_type`, `entity_id`, `occurred_at`"),
        ("idx_audit_logs_operator_time", "`tenant_id`, `operator_id`, `occurred_at`"),
        ("idx_audit_logs_action_time", "`tenant_id`, `action_code`, `occurred_at`")]),
    ("llm_call_logs", [
        "`call_scene` VARCHAR(32) NOT NULL",
        "`biz_type` VARCHAR(32) NOT NULL",
        "`biz_id` BIGINT UNSIGNED NOT NULL",
        "`plugin_code` VARCHAR(64) NULL",
        "`platform_key` VARCHAR(64) NOT NULL",
        "`model_id` VARCHAR(128) NOT NULL",
        "`request_json` JSON NULL",
        "`response_json` JSON NULL",
        "`prompt_tokens` INT UNSIGNED NULL",
        "`completion_tokens` INT UNSIGNED NULL",
        "`total_tokens` INT UNSIGNED NULL",
        "`latency_ms` INT UNSIGNED NULL",
        "`status` VARCHAR(16) NOT NULL",
        "`error_message` VARCHAR(512) NULL",
        "`occurred_at` DATETIME(3) NOT NULL",
    ], None,
       [("idx_llm_call_logs_scene_time", "`tenant_id`, `call_scene`, `occurred_at`"),
        ("idx_llm_call_logs_biz", "`tenant_id`, `biz_type`, `biz_id`, `occurred_at`"),
        ("idx_llm_call_logs_model_time", "`tenant_id`, `platform_key`, `model_id`, `occurred_at`")]),
    # 8.3 tasks
    ("tasks", [
        "`task_code` VARCHAR(64) NOT NULL",
        "`owner_id` BIGINT UNSIGNED NOT NULL",
        "`title` VARCHAR(128) NOT NULL",
        "`description_text` TEXT NULL",
        "`description_rich` MEDIUMTEXT NULL",
        "`scene_code` VARCHAR(64) NOT NULL DEFAULT 'GENERAL'",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'DRAFT'",
        "`distribute_strategy` VARCHAR(32) NOT NULL DEFAULT 'FIRST_COME'",
        "`quota` INT UNSIGNED NOT NULL DEFAULT 0",
        "`max_claim_per_user` INT UNSIGNED NOT NULL DEFAULT 0",
        "`acceptance_required_flag` TINYINT UNSIGNED NOT NULL DEFAULT 1",
        "`acceptance_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`latest_acceptance_id` BIGINT UNSIGNED NULL",
        "`reward_settlement_status` VARCHAR(16) NOT NULL DEFAULT 'DRAFT'",
        "`deadline_at` DATETIME(3) NULL",
        "`published_at` DATETIME(3) NULL",
        "`paused_at` DATETIME(3) NULL",
        "`finished_at` DATETIME(3) NULL",
        "`archived_at` DATETIME(3) NULL",
        "`restored_at` DATETIME(3) NULL",
        "`current_template_version_id` BIGINT UNSIGNED NULL",
        "`tags_json` JSON NULL",
        "`reward_rule_json` JSON NULL",
        "`settings_json` JSON NULL",
        "`published_check_result_json` JSON NULL",
        "`status_reason` VARCHAR(255) NULL",
        "`version_no` INT UNSIGNED NOT NULL DEFAULT 1",
    ], [("uk_tasks_code", "`tenant_id`, `task_code`, `deleted_flag`")],
       [("idx_tasks_owner_status", "`tenant_id`, `owner_id`, `status`, `updated_at`"),
        ("idx_tasks_status_deadline", "`tenant_id`, `status`, `deadline_at`, `id`"),
        ("idx_tasks_current_template", "`tenant_id`, `current_template_version_id`")]),
    ("task_members", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`user_id` BIGINT UNSIGNED NOT NULL",
        "`member_role` VARCHAR(32) NOT NULL",
        "`permission_set_json` JSON NOT NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
        "`joined_at` DATETIME(3) NOT NULL",
    ], [("uk_task_members", "`tenant_id`, `task_id`, `user_id`, `member_role`, `deleted_flag`")],
       [("idx_task_members_user", "`tenant_id`, `user_id`, `status`, `task_id`"),
        ("idx_task_members_task", "`tenant_id`, `task_id`, `member_role`, `status`")]),
    ("task_item_import_batches", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`source_file_id` BIGINT UNSIGNED NULL",
        "`source_filename` VARCHAR(255) NOT NULL",
        "`source_format` VARCHAR(16) NOT NULL",
        "`import_status` VARCHAR(16) NOT NULL DEFAULT 'RUNNING'",
        "`overwrite_mode` VARCHAR(16) NOT NULL DEFAULT 'REPLACE'",
        "`file_checksum` CHAR(64) NULL",
        "`total_rows` INT UNSIGNED NOT NULL DEFAULT 0",
        "`success_rows` INT UNSIGNED NOT NULL DEFAULT 0",
        "`failed_rows` INT UNSIGNED NOT NULL DEFAULT 0",
        "`error_summary_json` JSON NULL",
        "`started_at` DATETIME(3) NOT NULL",
        "`finished_at` DATETIME(3) NULL",
    ], None,
       [("idx_task_item_import_batches_task_time", "`tenant_id`, `task_id`, `started_at`"),
        ("idx_task_item_import_batches_status", "`tenant_id`, `import_status`, `started_at`"),
        ("idx_task_item_import_batches_file", "`tenant_id`, `source_file_id`")]),
    ("task_item_import_errors", [
        "`batch_id` BIGINT UNSIGNED NOT NULL",
        "`row_no` INT UNSIGNED NOT NULL",
        "`error_code` VARCHAR(64) NOT NULL",
        "`error_message` VARCHAR(512) NOT NULL",
        "`raw_line_text` MEDIUMTEXT NULL",
        "`raw_payload_json` JSON NULL",
        "`normalized_payload_json` JSON NULL",
        "`is_blocking` TINYINT UNSIGNED NOT NULL DEFAULT 1",
    ], [("uk_task_item_import_errors_row", "`tenant_id`, `batch_id`, `row_no`, `error_code`, `deleted_flag`")],
       [("idx_task_item_import_errors_batch", "`tenant_id`, `batch_id`, `row_no`")]),
    ("task_items", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`import_batch_id` BIGINT UNSIGNED NULL",
        "`seq_no` INT UNSIGNED NOT NULL",
        "`source_item_key` VARCHAR(128) NULL",
        "`payload_json` JSON NOT NULL",
        "`payload_hash` CHAR(64) NULL",
        "`item_status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
        "`difficulty_level` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`current_assignment_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`current_approved_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`acceptance_sampled_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`disabled_reason` VARCHAR(255) NULL",
        "`last_accepted_at` DATETIME(3) NULL",
    ], [("uk_task_items_seq", "`tenant_id`, `task_id`, `seq_no`, `deleted_flag`")],
       [("idx_task_items_task_status_seq", "`tenant_id`, `task_id`, `item_status`, `seq_no`, `id`"),
        ("idx_task_items_batch", "`tenant_id`, `import_batch_id`, `seq_no`"),
        ("idx_task_items_source_key", "`tenant_id`, `task_id`, `source_item_key`")]),
    ("template_versions", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`version_no` INT UNSIGNED NOT NULL",
        "`template_name` VARCHAR(128) NOT NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'DRAFT'",
        "`is_current` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`schema_json` JSON NOT NULL",
        "`schema_checksum` CHAR(64) NOT NULL",
        "`review_prompt_template` MEDIUMTEXT NULL",
        "`review_output_schema_json` JSON NULL",
        "`review_workflow_json` JSON NULL",
        "`acceptance_rule_json` JSON NULL",
        "`llm_assist_config_json` JSON NULL",
        "`provider_platform_key` VARCHAR(64) NULL",
        "`model_id` VARCHAR(128) NULL",
        "`widget_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`required_field_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`validation_errors_json` JSON NULL",
        "`published_at` DATETIME(3) NULL",
        "`archived_at` DATETIME(3) NULL",
        "`archived_reason` VARCHAR(255) NULL",
    ], [("uk_template_versions_no", "`tenant_id`, `task_id`, `version_no`, `deleted_flag`")],
       [("idx_template_versions_current", "`tenant_id`, `task_id`, `is_current`, `status`"),
        ("idx_template_versions_task_time", "`tenant_id`, `task_id`, `version_no`"),
        ("idx_template_versions_checksum", "`tenant_id`, `schema_checksum`")]),
    ("template_version_fields", [
        "`template_version_id` BIGINT UNSIGNED NOT NULL",
        "`field_code` VARCHAR(64) NOT NULL",
        "`field_path` VARCHAR(128) NOT NULL",
        "`field_title` VARCHAR(128) NOT NULL",
        "`widget_type` VARCHAR(32) NOT NULL",
        "`value_type` VARCHAR(32) NOT NULL",
        "`is_required` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`is_display_only` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`sort_no` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`default_value_json` JSON NULL",
        "`validator_rule_json` JSON NULL",
        "`linkage_rule_json` JSON NULL",
        "`visibility_rule_json` JSON NULL",
        "`dependency_field_codes_json` JSON NULL",
        "`enum_options_json` JSON NULL",
        "`widget_config_json` JSON NULL",
    ], [("uk_template_version_fields_code", "`tenant_id`, `template_version_id`, `field_code`, `deleted_flag`")],
       [("idx_template_version_fields_sort", "`tenant_id`, `template_version_id`, `sort_no`"),
        ("idx_template_version_fields_widget", "`tenant_id`, `template_version_id`, `widget_type`")]),
    ("template_review_dimensions", [
        "`template_version_id` BIGINT UNSIGNED NOT NULL",
        "`dimension_key` VARCHAR(64) NOT NULL",
        "`dimension_name` VARCHAR(64) NOT NULL",
        "`dimension_desc` VARCHAR(255) NULL",
        "`weight` DECIMAL(5,2) NOT NULL DEFAULT 1.00",
        "`score_min` DECIMAL(6,2) NOT NULL DEFAULT 0.00",
        "`score_max` DECIMAL(6,2) NOT NULL DEFAULT 100.00",
        "`pass_threshold` DECIMAL(6,2) NULL",
        "`reject_threshold` DECIMAL(6,2) NULL",
        "`prompt_instruction` VARCHAR(512) NULL",
        "`manual_review_hint` VARCHAR(512) NULL",
        "`severity_level` VARCHAR(16) NOT NULL DEFAULT 'MEDIUM'",
        "`sort_no` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`required_flag` TINYINT UNSIGNED NOT NULL DEFAULT 1",
    ], [("uk_template_review_dimensions_key", "`tenant_id`, `template_version_id`, `dimension_key`, `deleted_flag`")],
       [("idx_template_review_dimensions_sort", "`tenant_id`, `template_version_id`, `sort_no`")]),
    # 8.4 labeling
    ("assignments", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`item_id` BIGINT UNSIGNED NOT NULL",
        "`slot_no` SMALLINT UNSIGNED NOT NULL DEFAULT 1",
        "`labeler_id` BIGINT UNSIGNED NULL",
        "`assign_type` VARCHAR(16) NOT NULL DEFAULT 'AUTO_CLAIM'",
        "`claim_source` VARCHAR(16) NOT NULL DEFAULT 'MARKET'",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'UNCLAIMED'",
        "`current_round_no` SMALLINT UNSIGNED NOT NULL DEFAULT 1",
        "`assigned_by` BIGINT UNSIGNED NULL",
        "`assigned_at` DATETIME(3) NULL",
        "`claimed_at` DATETIME(3) NULL",
        "`deadline_at` DATETIME(3) NULL",
        "`closed_at` DATETIME(3) NULL",
        "`canceled_at` DATETIME(3) NULL",
        "`revoked_at` DATETIME(3) NULL",
        "`cancel_reason` VARCHAR(255) NULL",
    ], [("uk_assignments_item_slot", "`tenant_id`, `item_id`, `slot_no`, `deleted_flag`")],
       [("idx_assignments_task_status", "`tenant_id`, `task_id`, `status`, `id`"),
        ("idx_assignments_labeler_status", "`tenant_id`, `labeler_id`, `status`, `updated_at`"),
        ("idx_assignments_task_item", "`tenant_id`, `task_id`, `item_id`")]),
    ("submissions", [
        "`assignment_id` BIGINT UNSIGNED NOT NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`item_id` BIGINT UNSIGNED NOT NULL",
        "`labeler_id` BIGINT UNSIGNED NOT NULL",
        "`current_template_version_id` BIGINT UNSIGNED NOT NULL",
        "`current_version_id` BIGINT UNSIGNED NULL",
        "`approved_version_id` BIGINT UNSIGNED NULL",
        "`current_round_no` SMALLINT UNSIGNED NOT NULL DEFAULT 1",
        "`current_status` VARCHAR(24) NOT NULL DEFAULT 'DRAFT'",
        "`current_review_level` VARCHAR(16) NULL",
        "`next_review_level` VARCHAR(16) NULL",
        "`draft_data_json` JSON NULL",
        "`draft_checksum` CHAR(64) NULL",
        "`draft_saved_at` DATETIME(3) NULL",
        "`submit_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`return_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`reopen_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`last_submitted_at` DATETIME(3) NULL",
        "`revision_required_at` DATETIME(3) NULL",
        "`revision_deadline_at` DATETIME(3) NULL",
        "`finalized_at` DATETIME(3) NULL",
        "`last_action_code` VARCHAR(64) NULL",
        "`last_action_at` DATETIME(3) NULL",
        "`last_return_reason_text` VARCHAR(1024) NULL",
        "`last_ai_review_id` BIGINT UNSIGNED NULL",
        "`last_review_record_id` BIGINT UNSIGNED NULL",
        "`version_no` INT UNSIGNED NOT NULL DEFAULT 1",
    ], [("uk_submissions_assignment", "`tenant_id`, `assignment_id`, `deleted_flag`")],
       [("idx_submissions_labeler_status", "`tenant_id`, `labeler_id`, `current_status`, `updated_at`"),
        ("idx_submissions_task_status", "`tenant_id`, `task_id`, `current_status`, `updated_at`"),
        ("idx_submissions_review_level", "`tenant_id`, `current_review_level`, `next_review_level`, `current_status`, `updated_at`"),
        ("idx_submissions_assignment", "`tenant_id`, `assignment_id`"),
        ("idx_submissions_version", "`tenant_id`, `current_version_id`, `approved_version_id`")]),
    ("submission_versions", [
        "`submission_id` BIGINT UNSIGNED NOT NULL",
        "`assignment_id` BIGINT UNSIGNED NOT NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`item_id` BIGINT UNSIGNED NOT NULL",
        "`labeler_id` BIGINT UNSIGNED NOT NULL",
        "`round_no` SMALLINT UNSIGNED NOT NULL",
        "`template_version_id` BIGINT UNSIGNED NOT NULL",
        "`submit_source` VARCHAR(16) NOT NULL DEFAULT 'MANUAL'",
        "`submit_data_json` JSON NOT NULL",
        "`submit_data_hash` CHAR(64) NOT NULL",
        "`previous_version_id` BIGINT UNSIGNED NULL",
        "`submitted_at` DATETIME(3) NOT NULL",
    ], [("uk_submission_versions_round", "`tenant_id`, `submission_id`, `round_no`, `deleted_flag`")],
       [("idx_submission_versions_submission_time", "`tenant_id`, `submission_id`, `round_no`"),
        ("idx_submission_versions_task_time", "`tenant_id`, `task_id`, `submitted_at`"),
        ("idx_submission_versions_template", "`tenant_id`, `template_version_id`, `submitted_at`")]),
    ("submission_status_histories", [
        "`submission_id` BIGINT UNSIGNED NOT NULL",
        "`submission_version_id` BIGINT UNSIGNED NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`assignment_id` BIGINT UNSIGNED NOT NULL",
        "`round_no` SMALLINT UNSIGNED NOT NULL",
        "`from_status` VARCHAR(24) NULL",
        "`to_status` VARCHAR(24) NOT NULL",
        "`action_code` VARCHAR(64) NOT NULL",
        "`operator_type` VARCHAR(16) NOT NULL",
        "`operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0",
        "`review_level` VARCHAR(16) NULL",
        "`batch_operation_key` VARCHAR(64) NULL",
        "`reason_code` VARCHAR(64) NULL",
        "`reason_text` VARCHAR(512) NULL",
        "`related_ai_review_id` BIGINT UNSIGNED NULL",
        "`related_review_record_id` BIGINT UNSIGNED NULL",
        "`request_id` VARCHAR(64) NULL",
        "`idempotency_key` VARCHAR(128) NULL",
        "`occurred_at` DATETIME(3) NOT NULL",
    ], [("uk_submission_status_histories_idem", "`tenant_id`, `submission_id`, `idempotency_key`, `deleted_flag`")],
       [("idx_submission_status_histories_submission_time", "`tenant_id`, `submission_id`, `occurred_at`"),
        ("idx_submission_status_histories_task_status_time", "`tenant_id`, `task_id`, `to_status`, `occurred_at`")]),
    ("llm_assist_records", [
        "`submission_id` BIGINT UNSIGNED NOT NULL",
        "`assignment_id` BIGINT UNSIGNED NOT NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`template_version_id` BIGINT UNSIGNED NOT NULL",
        "`field_code` VARCHAR(64) NOT NULL",
        "`platform_key` VARCHAR(64) NOT NULL",
        "`model_id` VARCHAR(128) NOT NULL",
        "`prompt_text` MEDIUMTEXT NOT NULL",
        "`response_text` MEDIUMTEXT NULL",
        "`parsed_output_json` JSON NULL",
        "`status` VARCHAR(16) NOT NULL",
        "`total_tokens` INT UNSIGNED NULL",
        "`latency_ms` INT UNSIGNED NULL",
        "`invoked_by` BIGINT UNSIGNED NOT NULL",
        "`invoked_at` DATETIME(3) NOT NULL",
    ], None,
       [("idx_llm_assist_records_submission_time", "`tenant_id`, `submission_id`, `invoked_at`"),
        ("idx_llm_assist_records_task_field", "`tenant_id`, `task_id`, `field_code`, `invoked_at`")]),
    ("ai_review_records", [
        "`submission_id` BIGINT UNSIGNED NOT NULL",
        "`submission_version_id` BIGINT UNSIGNED NOT NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`assignment_id` BIGINT UNSIGNED NOT NULL",
        "`review_round_no` SMALLINT UNSIGNED NOT NULL",
        "`platform_key` VARCHAR(64) NOT NULL",
        "`model_id` VARCHAR(128) NOT NULL",
        "`async_task_id` BIGINT UNSIGNED NULL",
        "`provider_request_id` VARCHAR(128) NULL",
        "`prompt_snapshot` MEDIUMTEXT NULL",
        "`input_snapshot_json` JSON NULL",
        "`output_schema_snapshot_json` JSON NULL",
        "`parsed_result_json` JSON NULL",
        "`raw_response_text` MEDIUMTEXT NULL",
        "`verdict` VARCHAR(16) NOT NULL",
        "`total_score` DECIMAL(6,2) NULL",
        "`summary_text` TEXT NULL",
        "`retry_no` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`status` VARCHAR(16) NOT NULL",
        "`failure_reason` VARCHAR(512) NULL",
        "`manual_retry_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`dead_letter_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`fallback_target_status` VARCHAR(24) NULL",
        "`started_at` DATETIME(3) NOT NULL",
        "`finished_at` DATETIME(3) NULL",
    ], [("uk_ai_review_records_retry", "`tenant_id`, `submission_version_id`, `retry_no`, `deleted_flag`")],
       [("idx_ai_review_records_submission_time", "`tenant_id`, `submission_id`, `finished_at`"),
        ("idx_ai_review_records_task_verdict", "`tenant_id`, `task_id`, `verdict`, `finished_at`"),
        ("idx_ai_review_records_status", "`tenant_id`, `status`, `started_at`")]),
    ("ai_review_dimension_scores", [
        "`ai_review_id` BIGINT UNSIGNED NOT NULL",
        "`dimension_key` VARCHAR(64) NOT NULL",
        "`dimension_name` VARCHAR(64) NOT NULL",
        "`score` DECIMAL(6,2) NOT NULL",
        "`weight` DECIMAL(5,2) NOT NULL DEFAULT 1.00",
        "`verdict` VARCHAR(16) NULL",
        "`comment_text` VARCHAR(512) NULL",
        "`sort_no` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
    ], [("uk_ai_review_dimension_scores", "`tenant_id`, `ai_review_id`, `dimension_key`, `deleted_flag`")],
       [("idx_ai_review_dimension_scores_sort", "`tenant_id`, `ai_review_id`, `sort_no`"),
        ("idx_ai_review_dimension_scores_dim", "`tenant_id`, `dimension_key`, `score`")]),
    ("review_records", [
        "`submission_id` BIGINT UNSIGNED NOT NULL",
        "`submission_version_id` BIGINT UNSIGNED NOT NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`assignment_id` BIGINT UNSIGNED NOT NULL",
        "`reviewer_id` BIGINT UNSIGNED NOT NULL",
        "`review_level` VARCHAR(16) NOT NULL",
        "`review_stage_no` SMALLINT UNSIGNED NOT NULL DEFAULT 1",
        "`review_node_code` VARCHAR(64) NULL",
        "`action` VARCHAR(16) NOT NULL",
        "`from_status` VARCHAR(24) NOT NULL",
        "`to_status` VARCHAR(24) NOT NULL",
        "`review_batch_key` VARCHAR(64) NULL",
        "`next_review_level` VARCHAR(16) NULL",
        "`is_final_decision` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`comment_text` TEXT NOT NULL",
        "`diff_json` JSON NULL",
        "`decided_at` DATETIME(3) NOT NULL",
    ], None,
       [("idx_review_records_submission_time", "`tenant_id`, `submission_id`, `decided_at`"),
        ("idx_review_records_reviewer_time", "`tenant_id`, `reviewer_id`, `decided_at`"),
        ("idx_review_records_task_action_time", "`tenant_id`, `task_id`, `action`, `decided_at`"),
        ("idx_review_records_batch", "`tenant_id`, `review_batch_key`"),
        ("idx_review_records_level_time", "`tenant_id`, `review_level`, `decided_at`")]),
    ("review_batch_operations", [
        "`batch_key` VARCHAR(64) NOT NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`operator_id` BIGINT UNSIGNED NOT NULL",
        "`review_level` VARCHAR(16) NOT NULL",
        "`batch_action` VARCHAR(16) NOT NULL",
        "`criteria_json` JSON NULL",
        "`target_total_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`success_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`failed_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`started_at` DATETIME(3) NULL",
        "`finished_at` DATETIME(3) NULL",
        "`failure_summary_json` JSON NULL",
    ], [("uk_review_batch_operations_key", "`tenant_id`, `batch_key`, `deleted_flag`")],
       [("idx_review_batch_operations_task_time", "`tenant_id`, `task_id`, `created_at`"),
        ("idx_review_batch_operations_operator_time", "`tenant_id`, `operator_id`, `created_at`"),
        ("idx_review_batch_operations_status", "`tenant_id`, `status`, `created_at`")]),
    # 8.5 files & export
    ("file_assets", [
        "`storage_provider` VARCHAR(16) NOT NULL",
        "`bucket_name` VARCHAR(64) NOT NULL",
        "`object_key` VARCHAR(255) NOT NULL",
        "`original_name` VARCHAR(255) NOT NULL",
        "`stored_name` VARCHAR(255) NULL",
        "`file_ext` VARCHAR(32) NULL",
        "`mime_type` VARCHAR(128) NULL",
        "`size_bytes` BIGINT UNSIGNED NOT NULL DEFAULT 0",
        "`sha256` CHAR(64) NULL",
        "`category_code` VARCHAR(32) NOT NULL",
        "`upload_status` VARCHAR(16) NOT NULL DEFAULT 'SUCCESS'",
        "`is_public` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`uploaded_by` BIGINT UNSIGNED NOT NULL DEFAULT 0",
        "`uploaded_at` DATETIME(3) NOT NULL",
        "`scan_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`last_accessed_at` DATETIME(3) NULL",
        "`expire_at` DATETIME(3) NULL",
    ], [("uk_file_assets_object", "`tenant_id`, `bucket_name`, `object_key`, `deleted_flag`")],
       [("idx_file_assets_sha256", "`tenant_id`, `sha256`, `size_bytes`"),
        ("idx_file_assets_category_time", "`tenant_id`, `category_code`, `uploaded_at`"),
        ("idx_file_assets_uploader_time", "`tenant_id`, `uploaded_by`, `uploaded_at`")]),
    ("file_references", [
        "`file_id` BIGINT UNSIGNED NOT NULL",
        "`biz_type` VARCHAR(32) NOT NULL",
        "`biz_id` BIGINT UNSIGNED NOT NULL",
        "`biz_sub_id` BIGINT UNSIGNED NULL",
        "`field_code` VARCHAR(64) NULL",
        "`relation_role` VARCHAR(32) NOT NULL",
        "`sort_no` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`ref_status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'",
    ], [("uk_file_references", "`tenant_id`, `file_id`, `biz_type`, `biz_id`, `biz_sub_id`, `field_code`, `deleted_flag`")],
       [("idx_file_references_biz", "`tenant_id`, `biz_type`, `biz_id`, `biz_sub_id`"),
        ("idx_file_references_file", "`tenant_id`, `file_id`, `ref_status`")]),
    ("export_jobs", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`biz_type` VARCHAR(32) NOT NULL DEFAULT 'APPROVED_DATA'",
        "`source_biz_id` BIGINT UNSIGNED NULL",
        "`requested_by` BIGINT UNSIGNED NOT NULL",
        "`export_scope` VARCHAR(32) NOT NULL DEFAULT 'APPROVED_ONLY'",
        "`template_scope` VARCHAR(32) NOT NULL DEFAULT 'BOUND_VERSION'",
        "`format_code` VARCHAR(16) NOT NULL",
        "`field_map_json` JSON NULL",
        "`field_rename_json` JSON NULL",
        "`filters_json` JSON NULL",
        "`acceptance_id` BIGINT UNSIGNED NULL",
        "`include_review_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`include_ai_review_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`progress_percent` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`total_records` INT UNSIGNED NOT NULL DEFAULT 0",
        "`exported_records` INT UNSIGNED NOT NULL DEFAULT 0",
        "`result_file_id` BIGINT UNSIGNED NULL",
        "`async_task_id` BIGINT UNSIGNED NULL",
        "`checksum` CHAR(64) NULL",
        "`error_message` VARCHAR(1024) NULL",
        "`started_at` DATETIME(3) NULL",
        "`finished_at` DATETIME(3) NULL",
        "`canceled_at` DATETIME(3) NULL",
        "`expire_at` DATETIME(3) NULL",
    ], None,
       [("idx_export_jobs_task_time", "`tenant_id`, `task_id`, `created_at`"),
        ("idx_export_jobs_status_time", "`tenant_id`, `status`, `created_at`"),
        ("idx_export_jobs_requester_time", "`tenant_id`, `requested_by`, `created_at`"),
        ("idx_export_jobs_async_task", "`tenant_id`, `async_task_id`")]),
    # 8.6 acceptance & reward
    ("task_acceptance_records", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`acceptance_type` VARCHAR(32) NOT NULL DEFAULT 'FINAL_CONFIRM'",
        "`accepted_by` BIGINT UNSIGNED NOT NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`sample_rule_json` JSON NULL",
        "`target_scope_json` JSON NULL",
        "`sample_total_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`sampled_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`pass_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`failed_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`comment_text` TEXT NULL",
        "`confirmed_at` DATETIME(3) NULL",
        "`reopened_at` DATETIME(3) NULL",
        "`archived_at` DATETIME(3) NULL",
    ], None,
       [("idx_task_acceptance_records_task_time", "`tenant_id`, `task_id`, `created_at`"),
        ("idx_task_acceptance_records_status", "`tenant_id`, `status`, `created_at`"),
        ("idx_task_acceptance_records_operator", "`tenant_id`, `accepted_by`, `created_at`")]),
    ("task_acceptance_samples", [
        "`acceptance_id` BIGINT UNSIGNED NOT NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`submission_id` BIGINT UNSIGNED NOT NULL",
        "`submission_version_id` BIGINT UNSIGNED NOT NULL",
        "`assignment_id` BIGINT UNSIGNED NOT NULL",
        "`labeler_id` BIGINT UNSIGNED NOT NULL",
        "`reviewer_id` BIGINT UNSIGNED NULL",
        "`sample_source` VARCHAR(16) NOT NULL DEFAULT 'AUTO'",
        "`sample_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`owner_decision` VARCHAR(16) NULL",
        "`owner_comment_text` TEXT NULL",
        "`checked_at` DATETIME(3) NULL",
    ], [("uk_task_acceptance_samples", "`tenant_id`, `acceptance_id`, `submission_version_id`, `deleted_flag`")],
       [("idx_task_acceptance_samples_task_time", "`tenant_id`, `task_id`, `checked_at`"),
        ("idx_task_acceptance_samples_submission", "`tenant_id`, `submission_id`, `submission_version_id`"),
        ("idx_task_acceptance_samples_labeler", "`tenant_id`, `labeler_id`, `checked_at`")]),
    ("reward_settlement_batches", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`batch_no` VARCHAR(64) NOT NULL",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'DRAFT'",
        "`settle_scope` VARCHAR(32) NOT NULL DEFAULT 'APPROVED_ONLY'",
        "`currency_code` VARCHAR(16) NOT NULL DEFAULT 'CNY'",
        "`reward_rule_snapshot_json` JSON NOT NULL",
        "`target_total_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`effective_total_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`user_total_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00",
        "`confirmed_by` BIGINT UNSIGNED NULL",
        "`confirmed_at` DATETIME(3) NULL",
        "`paid_at` DATETIME(3) NULL",
        "`reversed_at` DATETIME(3) NULL",
        "`export_file_id` BIGINT UNSIGNED NULL",
        "`remark` VARCHAR(512) NULL",
    ], [("uk_reward_settlement_batches_no", "`tenant_id`, `task_id`, `batch_no`, `deleted_flag`")],
       [("idx_reward_settlement_batches_task_time", "`tenant_id`, `task_id`, `created_at`"),
        ("idx_reward_settlement_batches_status", "`tenant_id`, `status`, `created_at`"),
        ("idx_reward_settlement_batches_confirmed_by", "`tenant_id`, `confirmed_by`, `confirmed_at`")]),
    ("reward_settlement_details", [
        "`batch_id` BIGINT UNSIGNED NOT NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`user_id` BIGINT UNSIGNED NOT NULL",
        "`submission_id` BIGINT UNSIGNED NOT NULL",
        "`submission_version_id` BIGINT UNSIGNED NOT NULL",
        "`assignment_id` BIGINT UNSIGNED NOT NULL",
        "`currency_code` VARCHAR(16) NOT NULL DEFAULT 'CNY'",
        "`amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`quality_score` DECIMAL(6,2) NULL",
        "`reward_reason` VARCHAR(255) NULL",
        "`calc_basis_json` JSON NULL",
        "`effective_at` DATETIME(3) NULL",
        "`settled_at` DATETIME(3) NULL",
        "`reversed_at` DATETIME(3) NULL",
    ], [("uk_reward_settlement_details_submission", "`tenant_id`, `batch_id`, `submission_version_id`, `deleted_flag`")],
       [("idx_reward_settlement_details_user_time", "`tenant_id`, `user_id`, `created_at`"),
        ("idx_reward_settlement_details_task_time", "`tenant_id`, `task_id`, `created_at`"),
        ("idx_reward_settlement_details_status", "`tenant_id`, `status`, `created_at`"),
        ("idx_reward_settlement_details_submission", "`tenant_id`, `submission_id`, `submission_version_id`")]),
    # 8.7 notify & stats
    ("notify_messages", [
        "`biz_type` VARCHAR(32) NOT NULL",
        "`biz_id` BIGINT UNSIGNED NOT NULL",
        "`scene_code` VARCHAR(64) NOT NULL",
        "`channel_code` VARCHAR(16) NOT NULL",
        "`receiver_scope` VARCHAR(32) NOT NULL",
        "`title` VARCHAR(256) NOT NULL",
        "`content_text` TEXT NULL",
        "`content_json` JSON NULL",
        "`channel_config_snapshot_json` JSON NULL",
        "`sender_id` BIGINT UNSIGNED NOT NULL DEFAULT 0",
        "`status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`retry_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0",
        "`provider_message_id` VARCHAR(128) NULL",
        "`read_receipt_required_flag` TINYINT UNSIGNED NOT NULL DEFAULT 0",
        "`planned_at` DATETIME(3) NULL",
        "`sent_at` DATETIME(3) NULL",
        "`canceled_at` DATETIME(3) NULL",
    ], None,
       [("idx_notify_messages_scene_status_time", "`tenant_id`, `scene_code`, `status`, `planned_at`"),
        ("idx_notify_messages_biz", "`tenant_id`, `biz_type`, `biz_id`, `created_at`"),
        ("idx_notify_messages_sender_time", "`tenant_id`, `sender_id`, `created_at`")]),
    ("notify_message_receipts", [
        "`message_id` BIGINT UNSIGNED NOT NULL",
        "`receiver_type` VARCHAR(16) NOT NULL",
        "`receiver_key` VARCHAR(128) NOT NULL",
        "`receiver_user_id` BIGINT UNSIGNED NULL",
        "`delivery_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING'",
        "`error_message` VARCHAR(512) NULL",
        "`delivered_at` DATETIME(3) NULL",
        "`read_at` DATETIME(3) NULL",
    ], [("uk_notify_message_receipts", "`tenant_id`, `message_id`, `receiver_type`, `receiver_key`, `deleted_flag`")],
       [("idx_notify_message_receipts_user", "`tenant_id`, `receiver_user_id`, `delivery_status`, `created_at`"),
        ("idx_notify_message_receipts_message", "`tenant_id`, `message_id`, `delivery_status`")]),
    ("task_stats_snapshot", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`item_total_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`available_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`claimed_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`in_progress_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`submitted_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`ai_reviewing_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`ai_rejected_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`human_reviewing_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`needs_revision_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`returned_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`approved_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`rejected_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`first_pass_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`exportable_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`exported_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`active_labeler_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`active_reviewer_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`avg_ai_score` DECIMAL(6,2) NULL",
        "`avg_review_duration_sec` INT UNSIGNED NULL",
        "`last_export_at` DATETIME(3) NULL",
        "`refreshed_at` DATETIME(3) NOT NULL",
    ], [("uk_task_stats_snapshot", "`tenant_id`, `task_id`, `deleted_flag`")],
       [("idx_task_stats_snapshot_exportable", "`tenant_id`, `exportable_count`")]),
    ("task_stats_daily", [
        "`task_id` BIGINT UNSIGNED NOT NULL",
        "`stat_date` DATE NOT NULL",
        "`claim_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`submit_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`revision_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`ai_reject_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`approve_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`reject_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`return_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`first_pass_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`export_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`active_labeler_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`active_reviewer_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`avg_ai_score` DECIMAL(6,2) NULL",
        "`avg_cycle_time_sec` INT UNSIGNED NULL",
    ], [("uk_task_stats_daily", "`tenant_id`, `task_id`, `stat_date`, `deleted_flag`")],
       [("idx_task_stats_daily_date", "`tenant_id`, `stat_date`, `task_id`")]),
    ("user_stats_daily", [
        "`user_id` BIGINT UNSIGNED NOT NULL",
        "`role_code` VARCHAR(32) NOT NULL",
        "`task_id` BIGINT UNSIGNED NOT NULL DEFAULT 0",
        "`stat_date` DATE NOT NULL",
        "`claim_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`submit_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`draft_save_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`approve_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`reject_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`return_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`llm_assist_count` INT UNSIGNED NOT NULL DEFAULT 0",
        "`avg_submit_latency_sec` INT UNSIGNED NULL",
        "`avg_review_latency_sec` INT UNSIGNED NULL",
        "`quality_score_avg` DECIMAL(6,2) NULL",
        "`reward_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00",
        "`settled_reward_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00",
    ], [("uk_user_stats_daily", "`tenant_id`, `user_id`, `role_code`, `task_id`, `stat_date`, `deleted_flag`")],
       [("idx_user_stats_daily_user_date", "`tenant_id`, `user_id`, `stat_date`"),
        ("idx_user_stats_daily_task_role", "`tenant_id`, `task_id`, `role_code`, `stat_date`")]),
]

ORDER = [
    "users", "roles", "permissions", "role_permissions", "user_roles",
    "sys_menus", "role_menus", "auth_sessions", "auth_refresh_tokens",
    "system_clients", "sys_dict_types", "sys_dict_items", "plugin_registry",
    "plg_agent_provider_configs",
    "tasks", "task_members", "task_item_import_batches", "task_item_import_errors",
    "task_items", "template_versions", "template_version_fields", "template_review_dimensions",
    "assignments", "submissions", "submission_versions", "submission_status_histories",
    "llm_assist_records", "ai_review_records", "ai_review_dimension_scores",
    "review_records", "review_batch_operations",
    "file_assets", "file_references", "export_jobs",
    "task_acceptance_records", "task_acceptance_samples",
    "reward_settlement_batches", "reward_settlement_details",
    "notify_messages", "notify_message_receipts",
    "task_stats_snapshot", "task_stats_daily", "user_stats_daily",
    "async_tasks", "audit_logs", "llm_call_logs",
]

FK_CONSTRAINTS = [
    ("role_permissions", "fk_role_permissions_role", "role_id", "roles", "id"),
    ("role_permissions", "fk_role_permissions_permission", "permission_id", "permissions", "id"),
    ("user_roles", "fk_user_roles_user", "user_id", "users", "id"),
    ("user_roles", "fk_user_roles_role", "role_id", "roles", "id"),
    ("role_menus", "fk_role_menus_role", "role_id", "roles", "id"),
    ("role_menus", "fk_role_menus_menu", "menu_id", "sys_menus", "id"),
    ("auth_sessions", "fk_auth_sessions_user", "user_id", "users", "id"),
    ("auth_refresh_tokens", "fk_auth_refresh_tokens_session", "session_id", "auth_sessions", "id"),
    ("auth_refresh_tokens", "fk_auth_refresh_tokens_user", "user_id", "users", "id"),
    ("sys_dict_items", "fk_sys_dict_items_type", "dict_type_id", "sys_dict_types", "id"),
    ("task_members", "fk_task_members_task", "task_id", "tasks", "id"),
    ("task_members", "fk_task_members_user", "user_id", "users", "id"),
    ("task_item_import_errors", "fk_task_item_import_errors_batch", "batch_id", "task_item_import_batches", "id"),
    ("template_version_fields", "fk_template_version_fields_version", "template_version_id", "template_versions", "id"),
    ("template_review_dimensions", "fk_template_review_dimensions_version", "template_version_id", "template_versions", "id"),
    ("ai_review_dimension_scores", "fk_ai_review_dimension_scores_review", "ai_review_id", "ai_review_records", "id"),
    ("file_references", "fk_file_references_file", "file_id", "file_assets", "id"),
    ("task_acceptance_samples", "fk_task_acceptance_samples_acceptance", "acceptance_id", "task_acceptance_records", "id"),
    ("reward_settlement_details", "fk_reward_settlement_details_batch", "batch_id", "reward_settlement_batches", "id"),
    ("notify_message_receipts", "fk_notify_message_receipts_message", "message_id", "notify_messages", "id"),
]

by_name = {t[0]: t for t in TABLES}

def main():
    out = Path(__file__).resolve().parents[1] / "db" / "migration" / "V1__labelhub_init_schema.sql"
    lines = [
        "-- LabelHub 初始化 DDL",
        "-- 来源: docs/database-design.md",
        "-- MySQL 8.0+ / InnoDB / utf8mb4_0900_ai_ci",
        "-- 主键由应用侧发号（雪花/Leaf），非 AUTO_INCREMENT",
        "",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS = 0;",
        "",
    ]
    sections = [
        ("-- ========== 第一批：系统基础 ==========", ORDER[:14]),
        ("-- ========== 第二批：任务与模板 ==========", ORDER[14:22]),
        ("-- ========== 第三批：生产主链路 ==========", ORDER[22:31]),
        ("-- ========== 第四批：导出、验收、结算、文件、通知、统计、运行支撑 ==========", ORDER[31:]),
    ]
    for header, names in sections:
        lines.append(header)
        lines.append("")
        for name in names:
            t = by_name[name]
            lines.append(create_table(t[0], t[1], t[2] if len(t) > 2 else None, t[3] if len(t) > 3 else None))
            lines.append("")
    lines.append("-- ========== 物理外键（仅低频强约束表） ==========")
    lines.append("")
    for table, cname, col, ref_table, ref_col in FK_CONSTRAINTS:
        lines.append(
            f"ALTER TABLE `{table}` ADD CONSTRAINT `{cname}` "
            f"FOREIGN KEY (`{col}`) REFERENCES `{ref_table}` (`{ref_col}`);"
        )
    lines.append("")
    lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out} ({len(lines)} lines, {len(ORDER)} tables, {len(FK_CONSTRAINTS)} FKs)")


if __name__ == "__main__":
    main()
